### ISSUE TITLE
补充：让子弹飞 在b站是有资源的

### ISSUE THREAD

**Issue by XuLongjia** [Mayandev/douban250-in-bilibili#1]
https://www.bilibili.com/bangumi/play/ep199612?theme=movie%3Ffrom%3Dsearch&seid=8767783766180061528

**Comment by Mayandev** [comment]
> https://www.bilibili.com/bangumi/play/ep199612?theme=movie%3Ffrom%3Dsearch&seid=8767783766180061528

感谢提供信息🙏，已添加至 readme

**Comment by duoluodexiaoxiaoyuan** [comment]
这个仓库很有意义，但是我有一个好奇的点，这里面的资源是你每次在本地启动然后更新的吗，我看工作流里面执行的是js文件，好像python文件没有执行，我对工作流这块不太熟悉。我大概看了下思路是通过py爬取资源生成csv文件，然后通过工作流执行script.js文件来整体，我好奇py为什么没有在工作流中执行呢
